import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Hero from '../../components/Hero'
import Zoom from 'react-medium-image-zoom'
import 'react-medium-image-zoom/dist/styles.css'

import { SliderData } from '../../components/SliderData'
import Slider from '../../components/Slider'
import { Instagram } from '../../components/Instagram'
import img5 from '../../public/images/ig-img-1.jpeg'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        
        <title>Photography</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Hero heading = 'Peter McGuinness Photography' message=''/>
      <div className="container-medium-zoom">
            <Zoom  overlayBgColorEnd={'rgba(0, 0, 0, 0.94)'} >
                <img  alt="landscape" src='https://petermcguinnessphotography.com/static/media/25-31%20topazeded2%20Topaz%20Restyle%203.8d77f0fb.jpg'/>
            </Zoom>
          </div>
      <Slider slides={SliderData}/>



      <Instagram/>
    </div>
  );
}
